### ISSUE TITLE
Roll Crit icon not showing properly in V9

### ISSUE THREAD

**Issue by Kirwiisp** [FranzWarm/AlienCRT_UI#6] opened 2022-01-04 20:44 UTC
The heart beat icon isn't showing with the V9 core version, instead there is roll crit show weirdly 
![image](https://user-images.githubusercontent.com/59315476/148121498-f8733196-8961-47c4-b927-928524b059d1.png)

**Comment by Kirwiisp** [comment] 2022-01-08 08:43
In fact, it seems that the the alien crt actor sheet isn't selected by default 
![image](https://user-images.githubusercontent.com/59315476/148637957-4d5733ff-e56c-4de0-b464-b1a590daab57.png)

**Comment by FranzWarm** [comment] 2022-01-13 21:34
Hi! I have just updated the module. Please, try to update it and see if it works.

Merci!

**Comment by Kirwiisp** [comment] 2022-01-13 23:11
Hi ! Just update foundry (9.242)/system(2.0.7)/module (0.8)
And i still got this =>
![image](https://user-images.githubusercontent.com/59315476/149423166-235ad2cd-6e62-406d-b0e2-cf2c74044548.png)
If i manually select alien.aliencrtActorSheet it fix the sheet, but it's not selected by default

**Comment by andywingate** [comment] 2022-01-16 10:41
I have the same issue with the "roll for critical" button on the Actor sheet not looking right

**Comment by andywingate** [comment] 2022-01-16 10:48
> I have the same issue with the "roll for critical" button on the Actor sheet not looking right

Which is resolved when the correct sheet is selected as "this sheet" or "default"

![image](https://user-images.githubusercontent.com/749323/149656837-83835a4f-967a-4c49-9754-aae17430439a.png)

**Comment by FranzWarm** [comment] 2022-01-17 20:24
yes, I confirmed that the issue exists. I'll try to find someone to help me fix it (since I'm not a programmer). Thanks for bringing it to my attention!

**Comment by FranzWarm** [comment] 2022-01-18 23:47
alright! this issue is now fixed, thanks to @aMediocreDad !

**Closed as completed by FranzWarm** 2022-01-18 23:47 UTC
Labels: bug, help wanted
